spring.application.name=leave-management-system
debug=true

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/leave_management_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=mohith@0217
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate to automatically create/update tables based on your JPA entities.
